# the open api specification file for user service, restful api
openapi: 3.0.0
info:
  title: User Service
  description: User Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:

